version: "3.8"
services:
  node:
    build: ./docker/node
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh -c "cd react_src && npm install && npm start"
    ports:
      - "3000:3000"
